apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: mysql-service
spec:
  selector:
    app: sql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None