apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mysql-init-script
apiVersion: v1
data:
  init.sql: |+
    CREATE DATABASE IF NOT EXISTS weatherapp;
    CREATE USER 'authuser'@'%' IDENTIFIED BY 'my-secret-pw';
    GRANT ALL PRIVILEGES ON weatherapp.* TO 'authuser'@'%';
    FLUSH PRIVILEGES;