apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-weather
  labels:
    app.kubernetes.io/name: weatherapp-weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: weatherapp-weather
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weatherapp-weather
    spec:
      containers:
      - name: weather-container
        image: rawanhesham/weather:lab
        ports:
        - containerPort: 5000
          name: http-get
          protocol: TCP
        env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: api-sec
              key: apikey
        livenessProbe:
          httpGet:
            path: /
            port: http-get
        readinessProbe:
          httpGet:
            path: /
            port: http-get